development:
  # adapter: async
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379" } %>

test:
  adapter: test
  channel_prefix: vegaVPN_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: vegaVPN_production

